name: Qase Test Run with GitHub Link

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  QASE_PROJECT: ${{ vars.QASE_PROJECT }}  # Use project from variables

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create a Qase test run with GitHub Link
        uses: qase-tms/qase-action@v2
        with:
          command: run-create
          token: ${{ secrets.QASE_TOKEN }}
          project: ${{ env.QASE_PROJECT }}
          title: Manual API trigger!
          description: |
            Test Run Description  
            [GitHub Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          environment: my-env
          milestone: 123
          plan: 321
        id: qase-run-create

      - name: Set Qase Run Title
        run: echo "QASE_TESTOPS_RUN_TITLE=Manual API trigger!" >> $GITHUB_ENV

      - name: Run tests
        env:
          QASE_TESTOPS_PROJECT: ${{ env.QASE_PROJECT }}
          QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TOKEN }}
          QASE_TESTOPS_RUN_ID: ${{ steps.qase-run-create.outputs.id }}
        run: npm test

      - name: Complete a Qase test run
        uses: qase-tms/qase-action@v2
        with:
          command: run-complete
          token: ${{ secrets.QASE_TOKEN }}
          project: ${{ env.QASE_PROJECT }}
          id: ${{ steps.qase-run-create.outputs.id }}
        if: always() && steps.qase-run-create.result == 'success'
        id: complete
